### PR TITLE
Restore comments and disabled with comment

### PR DESCRIPTION
**Pull request by Fevix**

### CODE REVIEW

**Comment by AeolusDraco** [comment]
Is there anything that needs to be improved with this?

**Comment by Fevix** [comment]
Do you not see, right above your comment, where it says 'Fevix started a review'?

**Comment by AeolusDraco** [comment]
Here's what this looks like to me:
screenshot_1532829253

**Comment by AeolusDraco** [comment]
Reason for all the issues is that I used `git revert` to undo your changes, so everything you changed in the commits mentioned by the reversion commits which are commit 79774b201c32c3aa8f3078b6c846a7b27e049624, which reverts commits 71d45b0501cfa22a75b5ebe7c6927455bb266a59 and 3f11111d5525fa13a6d84118bbbe59eb165c563b. Then commit 2c934688c857e98824839ed7f0b4a7fa55df3696 which reverts commits a4207fa6518ce8abe314b52e0b2a3496b012226b and b10276e264e85e048524c94b84b9617e42e667a6.
In commit a4207fa6518ce8abe314b52e0b2a3496b012226b you removed the *.txt file. And in 
3f11111d5525fa13a6d84118bbbe59eb165c563b you removed trailing whitespace and and uncommented the racial descriptions in objects/wired/uplinkscanner/uplinkscanner.object.
Reversion commits undo everything in the requested commits.
However I am fixing the issues you stated.

**Comment by AeolusDraco** [comment]
The problem was from unrelated changes you made in the commits I reverted.
I probably shouldn't have reverted a4207fa6518ce8abe314b52e0b2a3496b012226b though.

**Pull request merged**
